### ISSUE TITLE
How to host bookie in a subdirectory

### ISSUE THREAD

**Issue by jpschewe** [bookieio/Bookie#210] opened 2013-04-28 19:03 UTC
I found the instructions at http://docs.bmark.us/en/latest/hosting.html on how to setup my own bookie instance. However it appears to assume that bookie is the only thing running on the website. Is there a way to host bookie in a subdirectory of an existing website? 

Here is my pyramid.wsgi:

``` python
from pyramid.paster import get_app
application = get_app('/home/jpschewe/projects/Bookie/bookie.ini', 'bookie')
```

Here is my wsgi conf:

```
WSGIApplicationGroup %{GLOBAL}
WSGIPassAuthorization On
WSGIDaemonProcess pyramid user=jpschewe group=jpschewe threads=4 \
    python-path=/home/jpschewe/projects/Bookie/lib/python2.6/site-packages
WSGIScriptAlias /bookie-jpschewe /home/jpschewe/projects/Bookie/pyramid.wsgi

<Directory /home/jpschewe/projects/Bookie>
    WSGIProcessGroup pyramid
    Order allow,deny
    Allow from all
</Directory>
```

However all of the links for search, login, etc. point to / instead of /bookie-jpschewe. I also notice that the source has all of the javascript served up from 127.0.0.1:8000, shouldn't this get handled by the WSGI?

**Comment by mitechie** [comment] 2013-04-28 19:06
This doesn't currently work. There's audit work that needs to go through to find cases of url generation that assumes the root directory. 

See #148

I'm going to close this as it's almost a dupe of #148.

**Closed as completed by mitechie** 2013-04-28 19:06 UTC

**Comment by jpschewe** [comment] 2013-04-28 19:07
OK, so I need to run another web server on an alternate port instead, correct?

**Comment by mitechie** [comment] 2013-04-28 19:13
Yes, or you can setup a sub-domain on your web server.

**Comment by jpschewe** [comment] 2013-04-28 19:15
OK, that would fix the URLs, how about the YUI combo loader?

**Comment by mitechie** [comment] 2013-04-28 19:23
So in the hosting directions you can host the combo loader on the same subdomain as long as you catch/rewrite the urls to the combo loader in the web server.

I've not done it in apache, but the nginx example has the match for /combo urls like so:

  location /combo {
    include     uwsgi_params;
    uwsgi_pass  unix:///tmp/convoy.sock;
    uwsgi_param UWSGI_SCHEME $scheme;
    break;
  }

**Comment by mitechie** [comment] 2013-04-28 19:24
You could also run the combo loader on it's own domain, just make sure you update the url/path for the combo loader in the .ini file you deploy with.

**Comment by jpschewe** [comment] 2013-05-27 23:10
I notice that there's nothing about the combo loader in the Apache hosting instructions. I suspect it would just be a simple redirect for /combo to the port that the combo loader is running on. Although I'm not entirely sure what would start the combo loader in the Apache instructions.

**Comment by mitechie** [comment] 2013-05-27 23:23
So the combo loader is just another wsgi service. It would need to be started/run just like the actual bookie app. I use an upstart script to start it for nginx. nginx then proxies requests through to the started service. 

The combo loader upstart is noted in the docs under the uwsgi section, which is the wsgi server used in that example.

http://docs.bmark.us/en/latest/hosting.html#uwsgi-config

You could probably setup another mod-wsgi section in apache for that. It can even be on a subdomain or subdirectory without an issue.

**Comment by jpschewe** [comment] 2013-05-28 02:12
Hmm, just adding another mod-wsgi section for a subdirectory doesn't work as the entry for bookie takes over all of the URL space.

I tried using combo.py as the target like pyramin.wsgi in the Apache instructions and that didn't work so good.

```
[Mon May 27 22:10:40 2013] [error] [client 66.41.133.245] mod_wsgi (pid=15444): Exception occurred processing WSGI script '/home/jpschewe/projects/bookie/production/combo.py'.
[Mon May 27 22:10:40 2013] [error] [client 66.41.133.245] Traceback (most recent call last):
[Mon May 27 22:10:40 2013] [error] [client 66.41.133.245]   File "/home/jpschewe/projects/bookie/production/lib/python2.6/site-packages/convoy/combo.py", line 126, in app
[Mon May 27 22:10:40 2013] [error] [client 66.41.133.245]     path_hint = parse_path_hint(environ['PATH_INFO'])
[Mon May 27 22:10:40 2013] [error] [client 66.41.133.245]   File "/home/jpschewe/projects/bookie/production/lib/python2.6/site-packages/convoy/combo.py", line 52, in parse_path_hint
[Mon May 27 22:10:40 2013] [error] [client 66.41.133.245]     path_hint = path.replace(combo_end.group(1), "").strip('/')
[Mon May 27 22:10:40 2013] [error] [client 66.41.133.245] AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by jcharaoui** [comment] 2014-05-03 01:23
Being able to run Bookie in a URL subdirectory would be awesome as it would allow us to host it behind HTTPS it without the need to obtain a new certificate.

**Comment by mitechie** [comment] 2014-05-05 00:51
Definitely agree. I want to try to get to this soon. It requires going through the urls and making sure to use url generation code to make routes vs hard coded. 

https://groups.google.com/forum/#!topic/pylons-discuss/AqKpuLoTAgU has some notes on the config to make it work after the url generation is updated.
