### ISSUE TITLE
Bookmark is added without URL

### ISSUE THREAD

**Issue by alexgalkin** [bookieio/Bookie#215] opened 2013-06-14 08:49 UTC
There should not be an ability to add bookmark without URL

**Comment by mitechie** [comment] 2013-06-14 11:23
I'm closing this as a duplicate of #199. I've started a branch to work on this. When validating a new bookmark, if it has an error, it tries to create an error message, but the auto transaction manager adds the bookmark to the db empty.

**Closed as completed by mitechie** 2013-06-14 11:23 UTC
